export default [
    {
        id:1,
        name:'Programming',
        icon:'/coding.webp',
        prompt:''
    },
    {
        id:2,
        name:'Health',
        icon:'/lotus.png',
        prompt:''
    },
    {
        id:3,
        name:'creative',
        icon:'/creative.webp',
        prompt:''
    }
]